### ISSUE TITLE
Reset brightness upon reload/next 

### ISSUE THREAD

**Issue by darknight-007** [dcunhas/agdss#12]
Currently, it seems the brightness value remains (hence, dvonne's issue?).

**Comment by dcunhas** [comment]
The sliders reset upon page reload, but do not when going to the next image. This is better, I feel, than them having to be reset by the user to whatever works best for them each time they go to a new image, especially since the lighting in the images is very similar. I can add a reset button to reset the values to default, but I don't want to autoreset.

**Comment by darknight-007** [comment]
We discussed this and agreed that it may be best to leave settings for now since the images might be similar (correlated in brightness properties, if from adjacent trees for example).
