### ISSUE TITLE
Error loading the image

### ISSUE THREAD

**Issue by Katawann** [dcunhas/agdss#32]
Hi,

I tried to test the labeling but I got "Error loading image" so I can't do anything. I'm on Windows 10 and I tried with Chrome, Firefox and Internet Explorer (who knows...) 

Sincerely,
Katawan

**Comment by darknight-007** [comment]
Hi Katawann, Thanks for trying AgDSS. I believe you are getting the error
since the AgDSS DB does not know yet what images are available for
labeling.

Can you copy this script to the folder where you have all your images, and
run it?
https://github.com/dcunhas/agdss/blob/master/addImages.sh
Afterwards, the error should go away. You can check by loading the admin
page and seeing if Images are available.

Regards,
-JD

**Comment by darknight-007** [comment]
Hi Katawann, 

Thanks for trying AgDSS. I believe you are getting the error since the AgDSS DB does not know yet what images are available for labeling. 

Can you copy this script to the folder where you have all your images, and run it? 
https://github.com/dcunhas/agdss/blob/master/addImages.sh
Afterwards, the error should go away. You can check by loading the admin page and seeing if Images are available. 

-JD
